ProgrammerBulkTest/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ProgrammerBulkTest.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('Quiz.urls')),
    # Match on the Quiz folder in a case insensitive way
    url(r'^(?i)quiz/', include('Quiz.urls')),
)

Quiz/urls.py
from django.conf.urls import patterns, url
from Quiz import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>\d+)/$', views.question, name='quiz'),
    url(r'^(?P<question_id>\d+)/answer/$', views.answer, name='answer')
)

Quiz/models.py
from django.db import models

# Create your models here.
class QuestionType(models.Model):
    name = models.CharField(max_length=50)
    has_choices = models.BooleanField()
    has_supporting_code = models.BooleanField()
    
    def __unicode__(self):
        return self.name

class Question(models.Model):
    instructions = models.TextField(blank=True,null=True)
    text = models.TextField(blank=True,null=True)
    code = models.TextField(blank=True,null=True)
    question_type = models.ForeignKey(QuestionType)
    is_demographic_question = models.BooleanField()
    
    def __unicode__(self):
        return self.text
    
class Answer(models.Model):
    question = models.ForeignKey(Question)
    language = models.CharField(max_length=50)
    answer = models.TextField()
    session = models.TextField()
    
    def __unicode__(self):
        return self.answer
    
class QuestionChoice(models.Model):
    question = models.ForeignKey(Question)
    text = models.TextField()
    
    def __unicdoe__(self):
        return self.question

Quiz/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader
import uuid

from Quiz.models import Question, QuestionChoice, QuestionType, Answer

# Create your views here.
def index(request):
    question_list = Question.objects.all()
    
    quid = request.session.get('QuizUUID', None)
    if quid == None:
        # Set the session key to a random UUID
        request.session['QuizUUID'] = str(uuid.uuid4())
    
    return render(request, 'questions/index.html', {'question_list':question_list})
    
def question(request, question_id, error_message=None):
    try:
        q = Question.objects.get(pk=question_id)
        t = QuestionType.objects.get(id=q.question_type_id)
        p, created = Answer.objects.get_or_create(question=q,session=request.session['QuizUUID'], defaults={'answer':"", 'language':""})
        sp = None if created else created
        context = {'question':q, 'question_type':t, 'previous_answer':p, 'show_previous':sp, 'error_message':error_message}
    except Question.DoesNotExist:
        question_list = Question.objects.all()
        return render(request, 'questions/index.html', {'question_list':question_list})
    return render(request, 'questions/question.html', context)
    
def answer(request, question_id, next_question=None):
    #return HttpResponse("This is the answer page") 
    try:
        r = request.POST['answer']
    except (KeyError):
        #question(request, question_id, error_message="You did not submit an answer.")
        q = Question.objects.get(pk=question_id)
        t = QuestionType.objects.get(id=q.question_type_id)
        p, created = Answer.objects.get_or_create(question=q,session=request.session['QuizUUID'], defaults={'answer':"", 'language':""})
        error_message = "You did not submit an answer"
        context = {'question':q, 'question_type':t, 'previous_answer':p, 'error_message':error_message}
        return render(request, 'questions/question.html', context)
    else:
        q = get_object_or_404(Question, id=question_id)
        if q.question_type.name == "LongAnswer":
            lang = request.POST['lang']
        else:
            lang = ""
        a = get_object_or_404(Answer, question=q, session=request.session['QuizUUID'])
        a.question = q
        a.session = request.session['QuizUUID']
        a.answer = str(r)
        a.language = lang
        a.save()
    
    return render(request, 'questions/answer.html', {'answer':a, 'previous':q.id-1, 'next':q.id+1})

        
    

Quiz/templates/questions/answer.html
{% if answer %}
<h1>Answer: {{ answer.question.id }}</h1>
<br />
Your response to question {{ answer.question.id }} has been recorded. Please proceed.
<br />
<br />
{% if answer.question.id != 1 %}
<a href="{% url 'quiz' previous %}">the previous question</a><br />
{% endif %}
<a href="{% url 'quiz' answer.question.id %}">this question again</a><br />
<a href="{% url 'quiz' next %}">the next question</a><br />
<a href="{% url 'index' %}">the index</a><br />
{% else %}
<p><strong>Error processing your answer. Please raise your hand to request assistance.</strong></p>
{% endif %}

Quiz/templates/questions/index.html
{% if question_list %}
	<ul>
		{% for q in question_list %}
			<li><a href="{% url 'quiz' q.id %}">Question: {{ q.id }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No questions are available at this time.</p>
{% endif %}

Quiz/templates/questions/question.html
{% load app_filters %}
{% if question %}
	<h1>Question {{ question.id }}</h1>
	
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<form action="{% url 'answer' question.id %}" method="post">
		{% csrf_token %}
	
	{% if question.instructions %}
	<p><strong>{{ question.instructions }}</strong></p><br />
	{% endif %}
	
	{% if question.code %}
	<p><i>Code for question {{ question.id }}</i></p>

	{{ question.code|pygmentize|safe }}<br />
	
	{% endif %}
	
	{{ question.text|safe }}<br />
	
	{% if question_type.name == 'MultipleChoice' %}
	{% for c in question.questionchoice_set.all %}
		<input type="radio" name="answer" id="choice{{ forloop.counter }}" value="{{ c.id }}" />
		<label for="choice{{ forloop.counter }}">{{ c.id }}: {{ c.text }}</label><br />
	{% endfor %}
	
	{% if show_previous %}
	<p><strong>Your previous answer was {{ previous_answer.answer }}. Please select it again before changing pages.</strong></p><br />
	{% endif %}
	{% endif %}
	
	{% if question_type.name == 'ShortAnswer' %}
		<input type="text" size=50 name="answer" value="{{ previous_answer.answer }}"/>
		<br />
	{% endif %}
	
	{% if question_type.name == 'LongAnswer' %}
		<p><i>Please indicate the language that your solution is in.</i></p>
		<input type="text" size=50 name="lang" value="{{ previous_answer.language }}"><br />
		<p><i>Your solution</i></p><br />
		<textarea cols="80" rows="50" name="answer">
			{{ previous_answer.answer }}
		</textarea>
	{% endif %}
	
	<br />
	<input type="submit" value="Submit Answer" name="submit-button"/>
{% else %}
	<p><strong>Unable to locate question.</strong></p>
{% endif %}
	